Getting data from github

In [49]:
import requests
import pandas as pd

In [51]:
#git raw link

url = 'https://raw.githubusercontent.com/WahuElizabethKE/synthetic_employees/refs/heads/main/MOCK_DATA%20(2).json'

In [52]:
#fetching data from Github

response = requests.get(url)

In [53]:
# Check if request was successful
if response.status_code == 200:
    print("✅ Successfully fetched data from GitHub!")
else:
    print("❌ Failed to fetch data. Check your URL.")
    exit()

✅ Successfully fetched data from GitHub!

In [57]:
#Convert JSON to Python list/dictionary
data = response.json()

In [58]:
#Convert to Pandas DataFrame
employee_df = pd.DataFrame(data)

In [60]:
#Display info
print(f"Dataset Shape: {employee_df.shape}")
print("\nFirst Few Rows:")
print(employee_df.head())

Dataset Shape: (100, 7)

First 5 rows:
   number              name  age  \
0       1   Marsha Stannett   32
1       2    Quincy Borrill   36
2       3     Sherie Brophy   30
3       4      Lyndsie Bode   55
4       5  Jesselyn Ferrara   44

                                         department     salary   join_date  \
0  error: undefined method `first' for nil:NilClass  126607.36   3/23/2023
1  error: undefined method `first' for nil:NilClass   58841.44   3/24/2023
2  error: undefined method `first' for nil:NilClass  147808.86   1/13/2025
3  error: undefined method `first' for nil:NilClass  179973.08  12/10/2022
4  error: undefined method `first' for nil:NilClass   80813.15   2/20/2024

          country
0         Georgia
1          France
2     Philippines
3  Czech Republic
4       Indonesia

In [79]:
#replacinng deparment error with unknown
employee_df['department'] = employee_df['department'].replace("error: undefined method `first' for nil:NilClass", 'finance')

In [80]:
#printing to see changes
print(employee_df['department'])

0     Unknown
1     Unknown
2     Unknown
3     Unknown
4     Unknown
       ...
95    Unknown
96    Unknown
97    Unknown
98    Unknown
99    Unknown
Name: department, Length: 100, dtype: object

In [81]:
employee_df['department'] = employee_df['department'].replace("Unknown", 'Finance')

In [82]:
#changing uknown to finance

print(employee_df['department'])

0     Finance
1     Finance
2     Finance
3     Finance
4     Finance
       ...
95    Finance
96    Finance
97    Finance
98    Finance
99    Finance
Name: department, Length: 100, dtype: object

In [84]:
print(employee_df )

    number               name  age department     salary   join_date  \
0        1    Marsha Stannett   32    Finance  126607.36   3/23/2023
1        2     Quincy Borrill   36    Finance   58841.44   3/24/2023
2        3      Sherie Brophy   30    Finance  147808.86   1/13/2025
3        4       Lyndsie Bode   55    Finance  179973.08  12/10/2022
4        5   Jesselyn Ferrara   44    Finance   80813.15   2/20/2024
..     ...                ...  ...        ...        ...         ...
95      96   Kirstyn Pitblado   51    Finance   65855.03    2/3/2022
96      97     Genni Ellerman   50    Finance  116874.54   9/16/2024
97      98  Rachelle Lavrinov   33    Finance   46669.05    5/4/2022
98      99      Kira Brunicke   37    Finance   63084.16   9/17/2024
99     100        Junina Dory   54    Finance   59530.65   5/24/2023

           country
0          Georgia
1           France
2      Philippines
3   Czech Republic
4        Indonesia
..             ...
95          Russia
96        Portugal
97           China
98           China
99           China

[100 rows x 7 columns]

In [87]:
employee_df[-5:]

    number               name  age department     salary  join_date   country
95      96   Kirstyn Pitblado   51    Finance   65855.03   2/3/2022    Russia
96      97     Genni Ellerman   50    Finance  116874.54  9/16/2024  Portugal
97      98  Rachelle Lavrinov   33    Finance   46669.05   5/4/2022     China
98      99      Kira Brunicke   37    Finance   63084.16  9/17/2024     China
99     100        Junina Dory   54    Finance   59530.65  5/24/2023     China

In [89]:
#Save the cleaned version

employee_df.to_csv("employees_clean.csv", index=False)
print("File saved as employees_clean.csv")

File saved as employees_clean.csv

In [2]:
import requests

In [3]:
#git url

url = "https://raw.githubusercontent.com/WahuElizabethKE/phone-store-data/refs/heads/main/MOCK_DATA%20(1).json"

In [4]:
#send request
phone_store_data = requests.get(url)

In [5]:
phone_data = phone_store_data.json()

In [6]:
#checking data type
# Python Lists vs. Dictionaries:
# Lists:
# - Ordered collection of items.
# - Items are accessed by their integer index (e.g., my_list[0]).
# - Can contain duplicate items.
# - Enclosed in square brackets [].
# Example: [1, 2, 3, 'apple', 'banana']

# Dictionaries:
# - Unordered collection of key-value pairs.
# - Items are accessed by their unique keys (e.g., my_dict['name']).
# - Keys must be unique and immutable (e.g., strings, numbers, tuples).
# - Values can be of any type and can be duplicated.
# - Enclosed in curly braces {} with key:value pairs.
# Example: {'name': 'Alice', 'age': 30, 'city': 'New York'}

# In your current notebook, 'phone_data' is a list of dictionaries.
# Each dictionary within the list represents a phone with keys like 'brand', 'year', 'price', etc.

type(phone_data)

list

In [7]:
phone_data

[{'brand': 'huawei',
  'year': 2015,
  'price': 1679,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2014,
  'price': 319,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'iphone',
  'year': 2019,
  'price': 254,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2022,
  'price': 479,
  'color': 'blue',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2018,
  'price': 943,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2015,
  'price': 1622,
  'color': 'blue',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2021,
  'price': 742,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'iphone',
  'year': 2019,
  'price': 840,
  'color': 'white',
  'storage_capacity': '128GB'},
 {'brand': 'redmi',
  'year': 2013,
  'price': 731,
  'color': 'white',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2013,
  'price': 178,
  'color': 'gold',
  'storage_capacity': '128GB'},
 {'brand': 'samsung',
  'year': 2019,
  'price': 725,
  'color': 'white',
  'storage_capacity': '128GB'},
 {'brand': 'samsung',
  'year': 2019,
  'price': 1942,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'redmi',
  'year': 2016,
  'price': 1566,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'redmi',
  'year': 2019,
  'price': 1662,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2011,
  'price': 1886,
  'color': 'white',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2021,
  'price': 883,
  'color': 'white',
  'storage_capacity': '64GB'},
 {'brand': 'iphone',
  'year': 2013,
  'price': 547,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2021,
  'price': 850,
  'color': 'white',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2012,
  'price': 707,
  'color': 'gold',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2022,
  'price': 1225,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2010,
  'price': 1914,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'redmi',
  'year': 2014,
  'price': 1683,
  'color': 'blue',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2021,
  'price': 1228,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2014,
  'price': 699,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'iphone',
  'year': 2021,
  'price': 725,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2022,
  'price': 323,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'redmi',
  'year': 2020,
  'price': 1932,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'redmi',
  'year': 2013,
  'price': 1139,
  'color': 'pink',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2013,
  'price': 1216,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2016,
  'price': 1752,
  'color': 'blue',
  'storage_capacity': '64GB'},
 {'brand': 'huawei',
  'year': 2010,
  'price': 1951,
  'color': 'pink',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2012,
  'price': 1607,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2011,
  'price': 1128,
  'color': 'blue',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2021,
  'price': 745,
  'color': 'black',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2015,
  'price': 1304,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'iphone',
  'year': 2011,
  'price': 332,
  'color': 'blue',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2022,
  'price': 506,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'iphone',
  'year': 2020,
  'price': 807,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'huawei',
  'year': 2015,
  'price': 1465,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2013,
  'price': 667,
  'color': 'blue',
  'storage_capacity': '64GB'},
 {'brand': 'redmi',
  'year': 2012,
  'price': 846,
  'color': 'black',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2015,
  'price': 1143,
  'color': 'blue',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2015,
  'price': 1711,
  'color': 'gold',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2012,
  'price': 1588,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'redmi',
  'year': 2021,
  'price': 1255,
  'color': 'pink',
  'storage_capacity': '128GB'},
 {'brand': 'redmi',
  'year': 2017,
  'price': 405,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'huawei',
  'year': 2013,
  'price': 1095,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2015,
  'price': 1692,
  'color': 'gold',
  'storage_capacity': '128GB'},
 {'brand': 'samsung',
  'year': 2012,
  'price': 624,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'huawei',
  'year': 2015,
  'price': 469,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2021,
  'price': 1074,
  'color': 'gold',
  'storage_capacity': '128GB'},
 {'brand': 'redmi',
  'year': 2020,
  'price': 1437,
  'color': 'blue',
  'storage_capacity': '64GB'},
 {'brand': 'redmi',
  'year': 2019,
  'price': 1310,
  'color': 'black',
  'storage_capacity': '64GB'},
 {'brand': 'iphone',
  'year': 2022,
  'price': 1869,
  'color': 'pink',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2017,
  'price': 831,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'huawei',
  'year': 2012,
  'price': 968,
  'color': 'black',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2017,
  'price': 690,
  'color': 'silver',
  'storage_capacity': '128GB'},
 {'brand': 'samsung',
  'year': 2013,
  'price': 832,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'huawei',
  'year': 2018,
  'price': 419,
  'color': 'blue',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2015,
  'price': 1567,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'huawei',
  'year': 2018,
  'price': 317,
  'color': 'silver',
  'storage_capacity': '256GB'},
 {'brand': 'redmi',
  'year': 2021,
  'price': 1228,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2017,
  'price': 711,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2015,
  'price': 815,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2021,
  'price': 1858,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2022,
  'price': 1852,
  'color': 'gold',
  'storage_capacity': '32GB'},
 {'brand': 'huawei',
  'year': 2015,
  'price': 1432,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2014,
  'price': 1552,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2019,
  'price': 1384,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2020,
  'price': 1292,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2022,
  'price': 147,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2014,
  'price': 830,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2012,
  'price': 772,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'redmi',
  'year': 2014,
  'price': 1546,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'iphone',
  'year': 2021,
  'price': 905,
  'color': 'pink',
  'storage_capacity': '64GB'},
 {'brand': 'huawei',
  'year': 2014,
  'price': 592,
  'color': 'silver',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2022,
  'price': 1566,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'redmi',
  'year': 2017,
  'price': 1746,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'iphone',
  'year': 2018,
  'price': 316,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2016,
  'price': 1126,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'iphone',
  'year': 2019,
  'price': 702,
  'color': 'silver',
  'storage_capacity': '256GB'},
 {'brand': 'redmi',
  'year': 2015,
  'price': 1259,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2018,
  'price': 1133,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2015,
  'price': 742,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'redmi',
  'year': 2021,
  'price': 1644,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'huawei',
  'year': 2018,
  'price': 248,
  'color': 'white',
  'storage_capacity': '256GB'},
 {'brand': 'iphone',
  'year': 2015,
  'price': 983,
  'color': 'blue',
  'storage_capacity': '64GB'},
 {'brand': 'redmi',
  'year': 2012,
  'price': 521,
  'color': 'white',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2022,
  'price': 1337,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2017,
  'price': 731,
  'color': 'black',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2014,
  'price': 1852,
  'color': 'black',
  'storage_capacity': '64GB'},
 {'brand': 'iphone',
  'year': 2020,
  'price': 924,
  'color': 'white',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2014,
  'price': 203,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'iphone',
  'year': 2021,
  'price': 104,
  'color': 'gold',
  'storage_capacity': '256GB'},
 {'brand': 'iphone',
  'year': 2018,
  'price': 1518,
  'color': 'blue',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2014,
  'price': 1416,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'iphone',
  'year': 2018,
  'price': 570,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2018,
  'price': 1468,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2020,
  'price': 1329,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2013,
  'price': 1767,
  'color': 'pink',
  'storage_capacity': '128GB'},
 {'brand': 'samsung',
  'year': 2019,
  'price': 1558,
  'color': 'white',
  'storage_capacity': '64GB'},
 {'brand': 'huawei',
  'year': 2019,
  'price': 1694,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2016,
  'price': 1398,
  'color': 'white',
  'storage_capacity': '128GB'},
 {'brand': 'iphone',
  'year': 2012,
  'price': 1141,
  'color': 'pink',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2010,
  'price': 157,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2018,
  'price': 1189,
  'color': 'pink',
  'storage_capacity': '64GB'},
 {'brand': 'redmi',
  'year': 2016,
  'price': 1472,
  'color': 'gold',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2011,
  'price': 1184,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2017,
  'price': 704,
  'color': 'gold',
  'storage_capacity': '32GB'},
 {'brand': 'iphone',
  'year': 2015,
  'price': 402,
  'color': 'blue',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2022,
  'price': 199,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2019,
  'price': 869,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'redmi',
  'year': 2015,
  'price': 896,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2015,
  'price': 1384,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2012,
  'price': 1307,
  'color': 'gold',
  'storage_capacity': '128GB'},
 {'brand': 'iphone',
  'year': 2015,
  'price': 1757,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2010,
  'price': 159,
  'color': 'gold',
  'storage_capacity': '256GB'},
 {'brand': 'iphone',
  'year': 2017,
  'price': 1912,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2020,
  'price': 912,
  'color': 'blue',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2016,
  'price': 973,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'redmi',
  'year': 2019,
  'price': 1134,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'huawei',
  'year': 2020,
  'price': 1870,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'iphone',
  'year': 2016,
  'price': 174,
  'color': 'gold',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2021,
  'price': 929,
  'color': 'gold',
  'storage_capacity': '256GB'},
 {'brand': 'huawei',
  'year': 2022,
  'price': 1583,
  'color': 'gold',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2022,
  'price': 657,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'samsung',
  'year': 2016,
  'price': 906,
  'color': 'pink',
  'storage_capacity': '64GB'},
 {'brand': 'iphone',
  'year': 2019,
  'price': 744,
  'color': 'silver',
  'storage_capacity': '128GB'},
 {'brand': 'iphone',
  'year': 2015,
  'price': 1909,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'samsung',
  'year': 2020,
  'price': 533,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'redmi',
  'year': 2010,
  'price': 1665,
  'color': 'white',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2022,
  'price': 187,
  'color': 'gold',
  'storage_capacity': '128GB'},
 {'brand': 'iphone',
  'year': 2019,
  'price': 614,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2017,
  'price': 104,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2018,
  'price': 1644,
  'color': 'gold',
  'storage_capacity': '32GB'},
 {'brand': 'huawei',
  'year': 2014,
  'price': 1584,
  'color': 'white',
  'storage_capacity': '64GB'},
 {'brand': 'iphone',
  'year': 2021,
  'price': 1038,
  'color': 'gold',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2013,
  'price': 1064,
  'color': 'black',
  'storage_capacity': '64GB'},
 {'brand': 'huawei',
  'year': 2016,
  'price': 1688,
  'color': 'black',
  'storage_capacity': '32GB'},
 {'brand': 'iphone',
  'year': 2022,
  'price': 525,
  'color': 'gold',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2019,
  'price': 1705,
  'color': 'white',
  'storage_capacity': '64GB'},
 {'brand': 'huawei',
  'year': 2020,
  'price': 1336,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2016,
  'price': 1219,
  'color': 'gold',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2013,
  'price': 1214,
  'color': 'gold',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2013,
  'price': 1761,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2015,
  'price': 710,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2021,
  'price': 1403,
  'color': 'black',
  'storage_capacity': '32GB'},
 {'brand': 'google pixel',
  'year': 2020,
  'price': 1107,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2019,
  'price': 1779,
  'color': 'pink',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2021,
  'price': 1303,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2013,
  'price': 1838,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'iphone',
  'year': 2010,
  'price': 1989,
  'color': 'silver',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2016,
  'price': 1598,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2010,
  'price': 1961,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'iphone',
  'year': 2020,
  'price': 205,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2015,
  'price': 220,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2013,
  'price': 1494,
  'color': 'blue',
  'storage_capacity': '32GB'},
 {'brand': 'iphone',
  'year': 2020,
  'price': 1999,
  'color': 'blue',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2020,
  'price': 1336,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2020,
  'price': 990,
  'color': 'black',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2019,
  'price': 572,
  'color': 'black',
  'storage_capacity': '64GB'},
 {'brand': 'huawei',
  'year': 2017,
  'price': 515,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'iphone',
  'year': 2016,
  'price': 1119,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'redmi',
  'year': 2021,
  'price': 1248,
  'color': 'blue',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2022,
  'price': 1215,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2013,
  'price': 1761,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2019,
  'price': 1078,
  'color': 'white',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2010,
  'price': 1830,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2018,
  'price': 1745,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'huawei',
  'year': 2011,
  'price': 554,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'iphone',
  'year': 2014,
  'price': 1707,
  'color': 'black',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2016,
  'price': 190,
  'color': 'pink',
  'storage_capacity': '32GB'},
 {'brand': 'samsung',
  'year': 2010,
  'price': 1196,
  'color': 'gold',
  'storage_capacity': '128GB'},
 {'brand': 'google pixel',
  'year': 2018,
  'price': 799,
  'color': 'black',
  'storage_capacity': '32GB'},
 {'brand': 'iphone',
  'year': 2019,
  'price': 1864,
  'color': 'white',
  'storage_capacity': '32GB'},
 {'brand': 'redmi',
  'year': 2013,
  'price': 718,
  'color': 'pink',
  'storage_capacity': '64GB'},
 {'brand': 'huawei',
  'year': 2018,
  'price': 1319,
  'color': 'gold',
  'storage_capacity': '64GB'},
 {'brand': 'huawei',
  'year': 2017,
  'price': 1149,
  'color': 'black',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2021,
  'price': 1877,
  'color': 'silver',
  'storage_capacity': '256GB'},
 {'brand': 'iphone',
  'year': 2010,
  'price': 1855,
  'color': 'blue',
  'storage_capacity': '256GB'},
 {'brand': 'samsung',
  'year': 2018,
  'price': 1830,
  'color': 'silver',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2016,
  'price': 418,
  'color': 'blue',
  'storage_capacity': '64GB'},
 {'brand': 'google pixel',
  'year': 2013,
  'price': 1239,
  'color': 'white',
  'storage_capacity': '256GB'},
 {'brand': 'huawei',
  'year': 2021,
  'price': 374,
  'color': 'black',
  'storage_capacity': '64GB'},
 {'brand': 'samsung',
  'year': 2019,
  'price': 1612,
  'color': 'pink',
  'storage_capacity': '64GB'},
 {'brand': 'iphone',
  'year': 2020,
  'price': 1630,
  'color': 'blue',
  'storage_capacity': '32GB'},
 {'brand': 'huawei',
  'year': 2015,
  'price': 338,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'iphone',
  'year': 2018,
  'price': 811,
  'color': 'pink',
  'storage_capacity': '256GB'},
 {'brand': 'google pixel',
  'year': 2010,

In [8]:
#viewing the last five dict

phone_data[-5:]

[{'brand': 'huawei',
  'year': 2010,
  'price': 903,
  'color': 'black',
  'storage_capacity': '128GB'},
 {'brand': 'redmi',
  'year': 2022,
  'price': 254,
  'color': 'silver',
  'storage_capacity': '32GB'},
 {'brand': 'iphone',
  'year': 2019,
  'price': 911,
  'color': 'pink',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2019,
  'price': 166,
  'color': 'silver',
  'storage_capacity': '128GB'},
 {'brand': 'huawei',
  'year': 2021,
  'price': 1733,
  'color': 'pink',
  'storage_capacity': '32GB'}]

In [9]:
#selecting one dict
phone_data_dict = phone_data[1]

phone_data = lists

phone_data_dict = dictionary

In [10]:
phone_data_dict

{'brand': 'google pixel',
 'year': 2014,
 'price': 319,
 'color': 'black',
 'storage_capacity': '128GB'}

In [11]:
print(phone_data_dict)

{'brand': 'google pixel', 'year': 2014, 'price': 319, 'color': 'black', 'storage_capacity': '128GB'}

In [12]:
type(phone_data_dict)

dict

In [13]:
#veiwing keys

phone_data_dict.keys()

dict_keys(['brand', 'year', 'price', 'color', 'storage_capacity'])

In [14]:
#veiwing values

phone_data_dict.values()

dict_values(['google pixel', 2014, 319, 'black', '128GB'])

In [15]:
#viewing some of the values

print("Brand:", phone_data_dict['brand'])
print("Year:", phone_data_dict['year'])
print("Price:", phone_data_dict['price'])

Brand: google pixel
Year: 2014
Price: 319

In [16]:
#gets key for price
phone_data_dict.get("price")

319

In [17]:
# Counting the number of dictionaries (items) in the list 'phone_data'
num_items = len(phone_data)
print(len(phone_data))

200

In [18]:
#adding new key = in_stock

for phone_data_dict in phone_data:
    phone_data_dict["in_stock"] = "yes"

In [19]:
#checking if it has been added

phone_data[50]

{'brand': 'samsung',
 'year': 2021,
 'price': 1074,
 'color': 'gold',
 'storage_capacity': '128GB',
 'in_stock': 'yes'}

In [20]:
# Get elements from index 10 to 14 (inclusive of 10, exclusive of 15)

in_stock = phone_data[10:15]
in_stock

[{'brand': 'samsung',
  'year': 2019,
  'price': 725,
  'color': 'white',
  'storage_capacity': '128GB',
  'in_stock': 'yes'},
 {'brand': 'samsung',
  'year': 2019,
  'price': 1942,
  'color': 'blue',
  'storage_capacity': '128GB',
  'in_stock': 'yes'},
 {'brand': 'redmi',
  'year': 2016,
  'price': 1566,
  'color': 'blue',
  'storage_capacity': '256GB',
  'in_stock': 'yes'},
 {'brand': 'redmi',
  'year': 2019,
  'price': 1662,
  'color': 'silver',
  'storage_capacity': '64GB',
  'in_stock': 'yes'},
 {'brand': 'samsung',
  'year': 2011,
  'price': 1886,
  'color': 'white',
  'storage_capacity': '128GB',
  'in_stock': 'yes'}]

In [21]:
for item in phone_data:
    print(item)

{'brand': 'huawei', 'year': 2015, 'price': 1679, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2014, 'price': 319, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2019, 'price': 254, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2022, 'price': 479, 'color': 'blue', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2018, 'price': 943, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2015, 'price': 1622, 'color': 'blue', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2021, 'price': 742, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2019, 'price': 840, 'color': 'white', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2013, 'price': 731, 'color': 'white', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2013, 'price': 178, 'color': 'gold', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2019, 'price': 725, 'color': 'white', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2019, 'price': 1942, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2016, 'price': 1566, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2019, 'price': 1662, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2011, 'price': 1886, 'color': 'white', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2021, 'price': 883, 'color': 'white', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2013, 'price': 547, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2021, 'price': 850, 'color': 'white', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2012, 'price': 707, 'color': 'gold', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2022, 'price': 1225, 'color': 'black', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2010, 'price': 1914, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2014, 'price': 1683, 'color': 'blue', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2021, 'price': 1228, 'color': 'pink', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2014, 'price': 699, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2021, 'price': 725, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2022, 'price': 323, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2020, 'price': 1932, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2013, 'price': 1139, 'color': 'pink', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2013, 'price': 1216, 'color': 'silver', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2016, 'price': 1752, 'color': 'blue', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2010, 'price': 1951, 'color': 'pink', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2012, 'price': 1607, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2011, 'price': 1128, 'color': 'blue', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2021, 'price': 745, 'color': 'black', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2015, 'price': 1304, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2011, 'price': 332, 'color': 'blue', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2022, 'price': 506, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2020, 'price': 807, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2015, 'price': 1465, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2013, 'price': 667, 'color': 'blue', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2012, 'price': 846, 'color': 'black', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2015, 'price': 1143, 'color': 'blue', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2015, 'price': 1711, 'color': 'gold', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2012, 'price': 1588, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2021, 'price': 1255, 'color': 'pink', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2017, 'price': 405, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2013, 'price': 1095, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2015, 'price': 1692, 'color': 'gold', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2012, 'price': 624, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2015, 'price': 469, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2021, 'price': 1074, 'color': 'gold', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2020, 'price': 1437, 'color': 'blue', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2019, 'price': 1310, 'color': 'black', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2022, 'price': 1869, 'color': 'pink', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2017, 'price': 831, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2012, 'price': 968, 'color': 'black', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2017, 'price': 690, 'color': 'silver', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2013, 'price': 832, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2018, 'price': 419, 'color': 'blue', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2015, 'price': 1567, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2018, 'price': 317, 'color': 'silver', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2021, 'price': 1228, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2017, 'price': 711, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2015, 'price': 815, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2021, 'price': 1858, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2022, 'price': 1852, 'color': 'gold', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2015, 'price': 1432, 'color': 'silver', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2014, 'price': 1552, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2019, 'price': 1384, 'color': 'black', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2020, 'price': 1292, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2022, 'price': 147, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2014, 'price': 830, 'color': 'black', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2012, 'price': 772, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2014, 'price': 1546, 'color': 'pink', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2021, 'price': 905, 'color': 'pink', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2014, 'price': 592, 'color': 'silver', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2022, 'price': 1566, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2017, 'price': 1746, 'color': 'black', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2018, 'price': 316, 'color': 'black', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2016, 'price': 1126, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2019, 'price': 702, 'color': 'silver', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2015, 'price': 1259, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2018, 'price': 1133, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2015, 'price': 742, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2021, 'price': 1644, 'color': 'pink', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2018, 'price': 248, 'color': 'white', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2015, 'price': 983, 'color': 'blue', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2012, 'price': 521, 'color': 'white', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2022, 'price': 1337, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2017, 'price': 731, 'color': 'black', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2014, 'price': 1852, 'color': 'black', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2020, 'price': 924, 'color': 'white', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2014, 'price': 203, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2021, 'price': 104, 'color': 'gold', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2018, 'price': 1518, 'color': 'blue', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2014, 'price': 1416, 'color': 'black', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2018, 'price': 570, 'color': 'pink', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2018, 'price': 1468, 'color': 'silver', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2020, 'price': 1329, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2013, 'price': 1767, 'color': 'pink', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2019, 'price': 1558, 'color': 'white', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2019, 'price': 1694, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2016, 'price': 1398, 'color': 'white', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2012, 'price': 1141, 'color': 'pink', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2010, 'price': 157, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2018, 'price': 1189, 'color': 'pink', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2016, 'price': 1472, 'color': 'gold', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2011, 'price': 1184, 'color': 'black', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2017, 'price': 704, 'color': 'gold', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2015, 'price': 402, 'color': 'blue', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2022, 'price': 199, 'color': 'pink', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2019, 'price': 869, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2015, 'price': 896, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2015, 'price': 1384, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2012, 'price': 1307, 'color': 'gold', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2015, 'price': 1757, 'color': 'silver', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2010, 'price': 159, 'color': 'gold', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2017, 'price': 1912, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2020, 'price': 912, 'color': 'blue', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2016, 'price': 973, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2019, 'price': 1134, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2020, 'price': 1870, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2016, 'price': 174, 'color': 'gold', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2021, 'price': 929, 'color': 'gold', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2022, 'price': 1583, 'color': 'gold', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2022, 'price': 657, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2016, 'price': 906, 'color': 'pink', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2019, 'price': 744, 'color': 'silver', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2015, 'price': 1909, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2020, 'price': 533, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2010, 'price': 1665, 'color': 'white', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2022, 'price': 187, 'color': 'gold', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2019, 'price': 614, 'color': 'black', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2017, 'price': 104, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2018, 'price': 1644, 'color': 'gold', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2014, 'price': 1584, 'color': 'white', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2021, 'price': 1038, 'color': 'gold', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2013, 'price': 1064, 'color': 'black', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2016, 'price': 1688, 'color': 'black', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2022, 'price': 525, 'color': 'gold', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2019, 'price': 1705, 'color': 'white', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2020, 'price': 1336, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2016, 'price': 1219, 'color': 'gold', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2013, 'price': 1214, 'color': 'gold', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2013, 'price': 1761, 'color': 'silver', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2015, 'price': 710, 'color': 'black', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2021, 'price': 1403, 'color': 'black', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2020, 'price': 1107, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2019, 'price': 1779, 'color': 'pink', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2021, 'price': 1303, 'color': 'silver', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2013, 'price': 1838, 'color': 'white', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2010, 'price': 1989, 'color': 'silver', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2016, 'price': 1598, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2010, 'price': 1961, 'color': 'silver', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2020, 'price': 205, 'color': 'pink', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2015, 'price': 220, 'color': 'silver', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2013, 'price': 1494, 'color': 'blue', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2020, 'price': 1999, 'color': 'blue', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2020, 'price': 1336, 'color': 'pink', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2020, 'price': 990, 'color': 'black', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2019, 'price': 572, 'color': 'black', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2017, 'price': 515, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2016, 'price': 1119, 'color': 'pink', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2021, 'price': 1248, 'color': 'blue', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'redmi', 'year': 2022, 'price': 1215, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2013, 'price': 1761, 'color': 'pink', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2019, 'price': 1078, 'color': 'white', 'storage_capacity': '128GB', 'in_stock': 'yes'}
{'brand': 'google pixel', 'year': 2010, 'price': 1830, 'color': 'blue', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2018, 'price': 1745, 'color': 'silver', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'huawei', 'year': 2011, 'price': 554, 'color': 'black', 'storage_capacity': '256GB', 'in_stock': 'yes'}
{'brand': 'iphone', 'year': 2014, 'price': 1707, 'color': 'black', 'storage_capacity': '64GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2016, 'price': 190, 'color': 'pink', 'storage_capacity': '32GB', 'in_stock': 'yes'}
{'brand': 'samsung', 'year': 2010, 'price': 1196, 'color': 'gold', 'storage_capacity': '128GB', 'in_stock': 'yes'}

In [22]:
# Initialize a variable to store the total price
total_price = 0

# Iterate through each dictionary in the phone_data list
for phone in phone_data:
    # Add the 'price' value of each phone to the total_price
    total_price += phone['price']

# Print the total sum of prices
print(f"The total sum of all phone prices is: {total_price}")

The total sum of all phone prices is: 217866

In [23]:
#sum of phone price

total_price = 0

for phone in phone_data:
  total_price += phone['price']

total_price

217866

In [24]:
#sliced data

in_stock = phone_data[10:15]
in_stock

[{'brand': 'samsung',
  'year': 2019,
  'price': 725,
  'color': 'white',
  'storage_capacity': '128GB',
  'in_stock': 'yes'},
 {'brand': 'samsung',
  'year': 2019,
  'price': 1942,
  'color': 'blue',
  'storage_capacity': '128GB',
  'in_stock': 'yes'},
 {'brand': 'redmi',
  'year': 2016,
  'price': 1566,
  'color': 'blue',
  'storage_capacity': '256GB',
  'in_stock': 'yes'},
 {'brand': 'redmi',
  'year': 2019,
  'price': 1662,
  'color': 'silver',
  'storage_capacity': '64GB',
  'in_stock': 'yes'},
 {'brand': 'samsung',
  'year': 2011,
  'price': 1886,
  'color': 'white',
  'storage_capacity': '128GB',
  'in_stock': 'yes'}]

In [25]:
import pandas

In [26]:
#creating a data frame
phone_df = pandas.DataFrame(in_stock)

In [27]:
phone_df

     brand  year  price   color storage_capacity in_stock
0  samsung  2019    725   white            128GB      yes
1  samsung  2019   1942    blue            128GB      yes
2    redmi  2016   1566    blue            256GB      yes
3    redmi  2019   1662  silver             64GB      yes
4  samsung  2011   1886   white            128GB      yes

In [54]:
#saving to cvs
phone_df.to_csv("phone_data.cvs", index=False)

In [55]:
print("phone_data.cvs saved successfully")

phone_data.cvs saved successfully

**Part 3**

In [30]:
#dummy
import requests

beauty_url = "https://dummyjson.com/products"

In [31]:
beauty_shop = requests.get(beauty_url)

beauty_data = beauty_shop.json()

In [32]:
print(type(beauty_data))

<class 'dict'>

In [33]:
beauty_data.keys()

dict_keys(['products', 'total', 'skip', 'limit'])

In [34]:
len(beauty_data)

4

In [35]:
beauty_data

{'products': [{'id': 1,
   'title': 'Essence Mascara Lash Princess',
   'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
   'category': 'beauty',
   'price': 9.99,
   'discountPercentage': 10.48,
   'rating': 2.56,
   'stock': 99,
   'tags': ['beauty', 'mascara'],
   'brand': 'Essence',
   'sku': 'BEA-ESS-ESS-001',
   'weight': 4,
   'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships in 3-5 business days',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 3,
     'comment': 'Would not recommend!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Eleanor Collins',
     'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Very satisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Lucas Gordon',
     'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Eleanor Collins',
     'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 48,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '5784719087687',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
  {'id': 2,
   'title': 'Eyeshadow Palette with Mirror',
   'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
   'category': 'beauty',
   'price': 19.99,
   'discountPercentage': 18.19,
   'rating': 2.86,
   'stock': 34,
   'tags': ['beauty', 'eyeshadow'],
   'brand': 'Glamour Beauty',
   'sku': 'BEA-GLA-EYE-002',
   'weight': 9,
   'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
   'warrantyInformation': '1 year warranty',
   'shippingInformation': 'Ships in 2 weeks',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Savannah Gomez',
     'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Awesome product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Christian Perez',
     'reviewerEmail': 'christian.perez@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nicholas Bailey',
     'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 20,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '9170275171413',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
  {'id': 3,
   'title': 'Powder Canister',
   'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
   'category': 'beauty',
   'price': 14.99,
   'discountPercentage': 9.84,
   'rating': 4.64,
   'stock': 89,
   'tags': ['beauty', 'face powder'],
   'brand': 'Velvet Touch',
   'sku': 'BEA-VEL-POW-003',
   'weight': 8,
   'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
   'warrantyInformation': '3 months warranty',
   'shippingInformation': 'Ships in 1-2 business days',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Alexander Jones',
     'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Elijah Cruz',
     'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Very dissatisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Avery Perez',
     'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 22,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '8418883906837',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'},
  {'id': 4,
   'title': 'Red Lipstick',
   'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
   'category': 'beauty',
   'price': 12.99,
   'discountPercentage': 12.16,
   'rating': 4.36,
   'stock': 91,
   'tags': ['beauty', 'lipstick'],
   'brand': 'Chic Cosmetics',
   'sku': 'BEA-CHI-LIP-004',
   'weight': 1,
   'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships in 1 week',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Liam Garcia',
     'reviewerEmail': 'liam.garcia@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Ruby Andrews',
     'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Clara Berry',
     'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 40,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '9467746727219',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'},
  {'id': 5,
   'title': 'Red Nail Polish',
   'description': 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
   'category': 'beauty',
   'price': 8.99,
   'discountPercentage': 11.44,
   'rating': 4.32,
   'stock': 79,
   'tags': ['beauty', 'nail polish'],
   'brand': 'Nail Couture',
   'sku': 'BEA-NAI-NAI-005',
   'weight': 8,
   'dimensions': {'width': 21.63, 'height': 16.48, 'depth': 29.84},
   'warrantyInformation': '1 month warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Benjamin Wilson',
     'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Liam Smith',
     'reviewerEmail': 'liam.smith@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Very unhappy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Clara Berry',
     'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 22,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '4063010628104',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp'},
  {'id': 6,
   'title': 'Calvin Klein CK One',
   'description': "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
   'category': 'fragrances',
   'price': 49.99,
   'discountPercentage': 1.89,
   'rating': 4.37,
   'stock': 29,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Calvin Klein',
   'sku': 'FRA-CAL-CAL-006',
   'weight': 7,
   'dimensions': {'width': 29.36, 'height': 27.76, 'depth': 20.72},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Very disappointed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Layla Young',
     'reviewerEmail': 'layla.young@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Fast shipping!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Daniel Cook',
     'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
    {'rating': 3,
     'comment': 'Not as described!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Jacob Cooper',
     'reviewerEmail': 'jacob.cooper@x.dummyjson.com'}],
   'returnPolicy': '90 days return policy',
   'minimumOrderQuantity': 9,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '2451534060749',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp'},
  {'id': 7,
   'title': 'Chanel Coco Noir Eau De',
   'description': 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
   'category': 'fragrances',
   'price': 129.99,
   'discountPercentage': 16.51,
   'rating': 4.26,
   'stock': 58,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Chanel',
   'sku': 'FRA-CHA-CHA-007',
   'weight': 7,
   'dimensions': {'width': 24.5, 'height': 25.7, 'depth': 25.98},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Ruby Andrews',
     'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Awesome product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Leah Henderson',
     'reviewerEmail': 'leah.henderson@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Xavier Wright',
     'reviewerEmail': 'xavier.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 1,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '4091737746820',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp'},
  {'id': 8,
   'title': "Dior J'adore",
   'description': "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
   'category': 'fragrances',
   'price': 89.99,
   'discountPercentage': 14.72,
   'rating': 3.8,
   'stock': 98,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Dior',
   'sku': 'FRA-DIO-DIO-008',
   'weight': 4,
   'dimensions': {'width': 27.67, 'height': 28.28, 'depth': 11.83},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships in 2 weeks',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 5,
     'comment': 'Great value for money!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nicholas Bailey',
     'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Great value for money!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Penelope Harper',
     'reviewerEmail': 'penelope.harper@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Emma Miller',
     'reviewerEmail': 'emma.miller@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 10,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '1445086097250',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ["https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp"],
   'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
  {'id': 9,
   'title': 'Dolce Shine Eau de',
   'description': "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
   'category': 'fragrances',
   'price': 69.99,
   'discountPercentage': 0.62,
   'rating': 3.96,
   'stock': 4,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Dolce & Gabbana',
   'sku': 'FRA-DOL-DOL-009',
   'weight': 6,
   'dimensions': {'width': 27.28, 'height': 29.88, 'depth': 18.3},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships in 1 month',
   'availabilityStatus': 'Low Stock',
   'reviews': [{'rating': 4,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Mateo Bennett',
     'reviewerEmail': 'mateo.bennett@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly recommended!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nolan Gonzalez',
     'reviewerEmail': 'nolan.gonzalez@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Aurora Lawson',
     'reviewerEmail': 'aurora.lawson@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 2,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3023868210708',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
  {'id': 10,
   'title': 'Gucci Bloom Eau de',
   'description': "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
   'category': 'fragrances',
   'price': 79.99,
   'discountPercentage': 14.39,
   'rating': 2.74,
   'stock': 91,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Gucci',
   'sku': 'FRA-GUC-GUC-010',
   'weight': 7,
   'dimensions': {'width': 20.92, 'height': 21.68, 'depth': 11.2},
   'warrantyInformation': '6 months warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 1,
     'comment': 'Very dissatisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Cameron Perez',
     'reviewerEmail': 'cameron.perez@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Daniel Cook',
     'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Addison Wright',
     'reviewerEmail': 'addison.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 2,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3170832177880',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp'},
  {'id': 11,
   'title': 'Annibale Colombo Bed',
   'description': 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
   'category': 'furniture',
   'price': 1899.99,
   'discountPercentage': 8.57,
   'rating': 4.77,
   'stock': 88,
   'tags': ['furniture', 'beds'],
   'brand': 'Annibale Colombo',
   'sku': 'FUR-ANN-ANN-011',
   'weight': 10,
   'dimensions': {'width': 28.16, 'height': 25.36, 'depth': 17.28},
   'warrantyInformation': '1 year warranty',
   'shippingInformation': 'Ships in 1 month',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Would not recommend!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Christopher West',
     'reviewerEmail': 'christopher.west@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Vivian Carter',
     'reviewerEmail': 'vivian.carter@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Mason Wright',
     'reviewerEmail': 'mason.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 1,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3610757456581',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
  {'id': 12,
   'title': 'Annibale Colombo Sofa',
   'description': 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
   'category': 'furniture',
   'price': 2499.99,
   'discountPercentage': 14.4,

In [36]:
import pandas as pd

In [37]:
#creating a data frame
beauty_df = pd.DataFrame(beauty_data['products'])

In [38]:
beauty_df

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
5,6,Calvin Klein CK One,CK One by Calvin Klein is a classic unisex fra...,fragrances,49.99,1.89,4.37,29,"[fragrances, perfumes]",Calvin Klein,...,"{'width': 29.36, 'height': 27.76, 'depth': 20.72}",1 week warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Very disappointed!'...",90 days return policy,9,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
6,7,Chanel Coco Noir Eau De,Coco Noir by Chanel is an elegant and mysterio...,fragrances,129.99,16.51,4.26,58,"[fragrances, perfumes]",Chanel,...,"{'width': 24.5, 'height': 25.7, 'depth': 25.98}",3 year warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly impressed!',...",No return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
7,8,Dior J'adore,J'adore by Dior is a luxurious and floral frag...,fragrances,89.99,14.72,3.80,98,"[fragrances, perfumes]",Dior,...,"{'width': 27.67, 'height': 28.28, 'depth': 11.83}",1 week warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great value for mon...",7 days return policy,10,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
8,9,Dolce Shine Eau de,Dolce Shine by Dolce & Gabbana is a vibrant an...,fragrances,69.99,0.62,3.96,4,"[fragrances, perfumes]",Dolce & Gabbana,...,"{'width': 27.28, 'height': 29.88, 'depth': 18.3}",3 year warranty,Ships in 1 month,Low Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",7 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
9,10,Gucci Bloom Eau de,Gucci Bloom by Gucci is a floral and captivati...,fragrances,79.99,14.39,2.74,91,"[fragrances, perfumes]",Gucci,...,"{'width': 20.92, 'height': 21.68, 'depth': 11.2}",6 months warranty,Ships overnight,In Stock,"[{'rating': 1, 'comment': 'Very dissatisfied!'...",No return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
10,11,Annibale Colombo Bed,The Annibale Colombo Bed is a luxurious and el...,furniture,1899.99,8.57,4.77,88,"[furniture, beds]",Annibale Colombo,...,"{'width': 28.16, 'height': 25.36, 'depth': 17.28}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 2, 'comment': 'Would not recommend...",No return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
11,12,Annibale Colombo Sofa,The Annibale Colombo Sofa is a sophisticated a...,furniture,2499.99,14.40,3.92,60,"[furniture, sofas]",Annibale Colombo,...,"{'width': 12.75, 'height': 20.55, 'depth': 19.06}",Lifetime warranty,Ships in 1 week,In Stock,"[{'rating': 3, 'comment': 'Very unhappy with m...",7 days return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
12,13,Bedside Table African Cherry,The Bedside Table in African Cherry is a styli...,furniture,299.99,19.09,2.87,64,"[furniture, bedside tables]",Furniture Co.,...,"{'width': 13.47, 'height': 24.99, 'depth': 27.35}",5 year warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Excellent quality!'...",7 days return policy,3,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
13,14,Knoll Saarinen Executive Conference Chair,The Knoll Saarinen Executive Conference Chair ...,furniture,499.99,2.01,4.88,26,"[furniture, office chairs]",Knoll,...,"{'width': 13.81, 'height': 7.5, 'depth': 5.62}",2 year warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Waste of money!', '...",60 days return policy,5,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
14,15,Wooden Bathroom Sink With Mirror,The Wooden Bathroom Sink with Mirror is a uniq...,furniture,799.99,8.80,3.59,7,"[furniture, bathroom]",Bath Trends,...,"{'width': 7.98, 'height': 8.88, 'depth': 28.46}",3 year warranty,Ships in 3-5 business days,Low Stock,"[{'rating': 4, 'comment': 'Fast shipping!', 'd...",60 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
15,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,[fruits],NaN,...,"{'width': 13.66, 'height': 11.01, 'depth': 9.73}",3 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very satisfied!', '...",90 days return policy,7,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
16,17,Beef Steak,"High-quality beef steak, great for grilling or...",groceries,12.99,9.61,4.47,86,[meat],NaN,...,"{'width': 18.9, 'height': 5.77, 'depth': 18.57}",3 year warranty,Ships overnight,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
17,18,Cat Food,Nutritious cat food formulated to meet the die...,groceries,8.99,9.58,3.13,46,"[pet supplies, cat food]",NaN,...,"{'width': 18.08, 'height': 9.26, 'depth': 21.86}",1 year warranty,Ships overnight,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,18,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
18,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,[meat],NaN,...,"{'width': 11.03, 'height': 22.11, 'depth': 16.01}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
19,20,Cooking Oil,"Versatile cooking oil suitable for frying, sau...",groceries,4.99,9.33,4.80,10,[cooking essentials],NaN,...,"{'width': 19.95, 'height': 27.54, 'depth': 24.86}",Lifetime warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Very happy with my ...",30 days return policy,46,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
20,21,Cucumber,"Crisp and hydrating cucumbers, ideal for salad...",groceries,1.49,0.16,4.07,84,[vegetables],NaN,...,"{'width': 12.8, 'height': 28.38, 'depth': 21.34}",2 year warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
21,22,Dog Food,Specially formulated dog food designed to prov...,groceries,10.99,10.27,4.55,71,"[pet supplies, dog food]",NaN,...,"{'width': 16.93, 'height': 27.15, 'depth': 9.29}",No warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
22,23,Eggs,"Fresh eggs, a versatile ingredient for baking,...",groceries,2.99,11.05,2.53,9,[dairy],NaN,...,"{'width': 11.42, 'height': 7.44, 'depth': 16.95}",1 week warranty,Ships in 1 week,In Stock,"[{'rating': 3, 'comment': 'Disappointing produ...",No return policy,32,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
23,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,[seafood],NaN,...,"{'width': 14.95, 'height': 26.31, 'depth': 11.27}",1 month warranty,Ships in 3-5 business days,In Stock,"[{'rating': 2, 'comment': 'Would not buy again...",60 days return policy,50,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
24,25,Green Bell Pepper,"Fresh and vibrant green bell pepper, perfect f...",groceries,1.29,0.16,3.25,33,[vegetables],NaN,...,"{'width': 15.33, 'height': 26.65, 'depth': 14.44}",1 month warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",30 days return policy,12,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
25,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,[vegetables],NaN,...,"{'width': 15.38, 'height': 18.12, 'depth': 19.92}",2 year warranty,Ships in 1 week,Low Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",30 days return policy,39,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
26,27,Honey Jar,"Pure and natural honey in a convenient jar, pe...",groceries,6.99,14.40,3.97,34,[condiments],NaN,...,"{'width': 9.28, 'height': 21.72, 'depth': 17.74}",1 month warranty,Ships in 1-2 business days,In Stock,"[{'rating': 1, 'comment': 'Very disappointed!'...",90 days return policy,47,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
27,28,Ice Cream,"Creamy and delicious ice cream, available in v...",groceries,5.49,8.69,3.39,27,[desserts],NaN,...,"{'width': 14.83, 'height': 15.07, 'depth': 24.2}",1 month warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very pleased!', 'da...",No return policy,42,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
28,29,Juice,"Refreshing fruit juice, packed with vitamins a...",groceries,3.99,12.06,3.94,50,[beverages],NaN,...,"{'width': 18.56, 'height': 21.46, 'depth': 28.02}",6 months warranty,Ships in 1 week,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",No return policy,25,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
29,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,[fruits],NaN,...,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...

In [39]:
#saving to cvs

beauty_df.to_csv("dummyjson_products.csv", index=False)
print("✅ Products saved to dummyjson_products.csv\n")

✅ Products saved to dummyjson_products.csv

#Carts

In [40]:
#carts
import requests
cart_url = "https://dummyjson.com/carts"

In [41]:
print("Fetching Carts...")

carts_response = requests.get(cart_url)

carts_data = carts_response.json()

Fetching Carts...

In [42]:
carts_data

{'carts': [{'id': 1,
   'products': [{'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 12.13,
     'discountedTotal': 105.41,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 113,
     'title': 'Generic Motorcycle',
     'price': 3999.99,
     'quantity': 3,
     'total': 11999.97,
     'discountPercentage': 12.1,
     'discountedTotal': 10547.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
    {'id': 122,
     'title': 'iPhone 6',
     'price': 299.99,
     'quantity': 3,
     'total': 899.97,
     'discountPercentage': 6.69,
     'discountedTotal': 839.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
    {'id': 138,
     'title': 'Baseball Ball',
     'price': 8.99,
     'quantity': 2,
     'total': 17.98,
     'discountPercentage': 1.71,
     'discountedTotal': 17.67,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}],
   'total': 13037.88,
   'discountedTotal': 11510.81,
   'userId': 1,
   'totalProducts': 4,
   'totalQuantity': 12},
  {'id': 2,
   'products': [{'id': 86,
     'title': 'Man Short Sleeve Shirt',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 6.83,
     'discountedTotal': 93.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
    {'id': 104,
     'title': 'Apple iPhone Charger',
     'price': 19.99,
     'quantity': 2,
     'total': 39.98,
     'discountPercentage': 18.52,
     'discountedTotal': 32.58,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'}],
   'total': 139.93,
   'discountedTotal': 125.7,
   'userId': 2,
   'totalProducts': 2,
   'totalQuantity': 7},
  {'id': 3,
   'products': [{'id': 24,
     'title': 'Fish Steak',
     'price': 14.99,
     'quantity': 1,
     'total': 14.99,
     'discountPercentage': 4.23,
     'discountedTotal': 14.36,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp'},
    {'id': 123,
     'title': 'iPhone 13 Pro',
     'price': 1099.99,
     'quantity': 1,
     'total': 1099.99,
     'discountPercentage': 9.37,
     'discountedTotal': 996.92,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
    {'id': 129,
     'title': 'Realme X',
     'price': 299.99,
     'quantity': 1,
     'total': 299.99,
     'discountPercentage': 6.95,
     'discountedTotal': 279.14,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp'},
    {'id': 86,
     'title': 'Man Short Sleeve Shirt',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 6.83,
     'discountedTotal': 93.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 2,
     'total': 179.98,
     'discountPercentage': 14.72,
     'discountedTotal': 153.49,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
    {'id': 157,
     'title': 'Party Glasses',
     'price': 19.99,
     'quantity': 5,
     'total': 99.94999999999999,
     'discountPercentage': 11.22,
     'discountedTotal': 88.74,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp'}],
   'total': 1794.85,
   'discountedTotal': 1625.77,
   'userId': 3,
   'totalProducts': 6,
   'totalQuantity': 15},
  {'id': 4,
   'products': [{'id': 92,
     'title': 'Sports Sneakers Off White Red',
     'price': 109.99,
     'quantity': 3,
     'total': 329.96999999999997,
     'discountPercentage': 0.04,
     'discountedTotal': 329.84,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 4,
     'total': 359.96,
     'discountPercentage': 14.72,
     'discountedTotal': 306.97,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"}],
   'total': 689.93,
   'discountedTotal': 636.81,
   'userId': 4,
   'totalProducts': 2,
   'totalQuantity': 7},
  {'id': 5,
   'products': [{'id': 161,
     'title': 'Samsung Galaxy Tab White',
     'price': 349.99,
     'quantity': 4,
     'total': 1399.96,
     'discountPercentage': 18.2,
     'discountedTotal': 1145.17,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'},
    {'id': 39,
     'title': 'Soft Drinks',
     'price': 1.99,
     'quantity': 4,
     'total': 7.96,
     'discountPercentage': 17.48,
     'discountedTotal': 6.57,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp'},
    {'id': 3,
     'title': 'Powder Canister',
     'price': 14.99,
     'quantity': 4,
     'total': 59.96,
     'discountPercentage': 9.84,
     'discountedTotal': 54.06,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'}],
   'total': 1467.88,
   'discountedTotal': 1205.8,
   'userId': 5,
   'totalProducts': 3,
   'totalQuantity': 12},
  {'id': 6,
   'products': [{'id': 192,
     'title': 'Rolex Datejust Women',
     'price': 10999.99,
     'quantity': 5,
     'total': 54999.95,
     'discountPercentage': 15.94,
     'discountedTotal': 46232.96,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp'},
    {'id': 130,
     'title': 'Realme XT',
     'price': 349.99,
     'quantity': 1,
     'total': 349.99,
     'discountPercentage': 11.51,
     'discountedTotal': 309.71,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp'},
    {'id': 155,
     'title': 'Classic Sun Glasses',
     'price': 24.99,
     'quantity': 4,
     'total': 99.96,
     'discountPercentage': 4.94,
     'discountedTotal': 95.02,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp'},
    {'id': 42,
     'title': 'Water',
     'price': 0.99,
     'quantity': 4,
     'total': 3.96,
     'discountPercentage': 14.92,
     'discountedTotal': 3.37,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp'}],
   'total': 55453.86,
   'discountedTotal': 46641.06,
   'userId': 6,
   'totalProducts': 4,
   'totalQuantity': 14},
  {'id': 7,
   'products': [{'id': 56,
     'title': 'Electric Stove',
     'price': 49.99,
     'quantity': 1,
     'total': 49.99,
     'discountPercentage': 14.04,
     'discountedTotal': 42.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
    {'id': 136,
     'title': 'Vivo X21',
     'price': 499.99,
     'quantity': 1,
     'total': 499.99,
     'discountPercentage': 17.41,
     'discountedTotal': 412.94,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp'},
    {'id': 9,
     'title': 'Dolce Shine Eau de',
     'price': 69.99,
     'quantity': 2,
     'total': 139.98,
     'discountPercentage': 0.62,
     'discountedTotal': 139.11,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
    {'id': 120,
     'title': 'Vaseline Men Body and Face Lotion',
     'price': 9.99,
     'quantity': 4,
     'total': 39.96,
     'discountPercentage': 13.39,
     'discountedTotal': 34.61,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp'},
    {'id': 56,
     'title': 'Electric Stove',
     'price': 49.99,
     'quantity': 1,
     'total': 49.99,
     'discountPercentage': 14.04,
     'discountedTotal': 42.97,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp'},
    {'id': 90,
     'title': 'Puma Future Rider Trainers',
     'price': 89.99,
     'quantity': 5,
     'total': 449.95,
     'discountPercentage': 4.2,
     'discountedTotal': 431.05,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
   'total': 1229.86,
   'discountedTotal': 1103.65,
   'userId': 7,
   'totalProducts': 6,
   'totalQuantity': 14},
  {'id': 8,
   'products': [{'id': 18,
     'title': 'Cat Food',
     'price': 8.99,
     'quantity': 2,
     'total': 17.98,
     'discountPercentage': 9.58,
     'discountedTotal': 16.26,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp'},
    {'id': 50,
     'title': 'Black Whisk',
     'price': 9.99,
     'quantity': 3,
     'total': 29.97,
     'discountPercentage': 10.24,
     'discountedTotal': 26.9,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp'},
    {'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 12.13,
     'discountedTotal': 105.41,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 11,
     'title': 'Annibale Colombo Bed',
     'price': 1899.99,
     'quantity': 3,
     'total': 5699.97,
     'discountPercentage': 8.57,
     'discountedTotal': 5211.48,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
    {'id': 108,
     'title': 'iPhone 12 Silicone Case with MagSafe Plum',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 13.85,
     'discountedTotal': 103.35,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'},
    {'id': 106,
     'title': 'Apple Watch Series 4 Gold',
     'price': 349.99,
     'quantity': 1,
     'total': 349.99,
     'discountPercentage': 12.02,
     'discountedTotal': 307.92,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp'}],
   'total': 6337.83,
   'discountedTotal': 5771.32,
   'userId': 8,
   'totalProducts': 6,
   'totalQuantity': 17},
  {'id': 9,
   'products': [{'id': 1,
     'title': 'Essence Mascara Lash Princess',
     'price': 9.99,
     'quantity': 3,
     'total': 29.97,
     'discountPercentage': 10.48,
     'discountedTotal': 26.83,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
    {'id': 98,
     'title': 'Rolex Submariner Watch',
     'price': 13999.99,
     'quantity': 2,
     'total': 27999.98,
     'discountPercentage': 5.05,
     'discountedTotal': 26585.98,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
    {'id': 132,
     'title': 'Samsung Galaxy S8',
     'price': 499.99,
     'quantity': 3,
     'total': 1499.97,
     'discountPercentage': 19.45,
     'discountedTotal': 1208.23,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp'},
    {'id': 90,
     'title': 'Puma Future Rider Trainers',
     'price': 89.99,
     'quantity': 2,
     'total': 179.98,
     'discountPercentage': 4.2,
     'discountedTotal': 172.42,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp'}],
   'total': 29709.9,
   'discountedTotal': 27993.46,
   'userId': 9,
   'totalProducts': 4,
   'totalQuantity': 10},
  {'id': 10,
   'products': [{'id': 41,
     'title': 'Tissue Paper Box',
     'price': 2.49,
     'quantity': 1,
     'total': 2.49,
     'discountPercentage': 13.28,
     'discountedTotal': 2.16,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp'},
    {'id': 108,
     'title': 'iPhone 12 Silicone Case with MagSafe Plum',
     'price': 29.99,
     'quantity': 5,
     'total': 149.95,
     'discountPercentage': 13.85,
     'discountedTotal': 129.18,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'}],
   'total': 152.44,
   'discountedTotal': 131.34,
   'userId': 10,
   'totalProducts': 2,
   'totalQuantity': 6},
  {'id': 11,
   'products': [{'id': 115,
     'title': 'MotoGP CI.H1',
     'price': 14999.99,
     'quantity': 4,
     'total': 59999.96,
     'discountPercentage': 6.92,
     'discountedTotal': 55847.96,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/thumbnail.webp'},
    {'id': 101,
     'title': 'Apple AirPods Max Silver',
     'price': 549.99,
     'quantity': 2,
     'total': 1099.98,
     'discountPercentage': 13.67,
     'discountedTotal': 949.61,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp'},
    {'id': 55,
     'title': 'Egg Slicer',
     'price': 6.99,
     'quantity': 4,
     'total': 27.96,
     'discountPercentage': 14.76,
     'discountedTotal': 23.83,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp'},
    {'id': 25,
     'title': 'Green Bell Pepper',
     'price': 1.29,
     'quantity': 3,
     'total': 3.87,
     'discountPercentage': 0.16,
     'discountedTotal': 3.86,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp'},
    {'id': 161,
     'title': 'Samsung Galaxy Tab White',
     'price': 349.99,
     'quantity': 2,
     'total': 699.98,
     'discountPercentage': 18.2,
     'discountedTotal': 572.58,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp'}],
   'total': 61831.75,
   'discountedTotal': 57397.84,
   'userId': 11,
   'totalProducts': 5,
   'totalQuantity': 15},
  {'id': 12,
   'products': [{'id': 117,
     'title': 'Sportbike Motorcycle',
     'price': 7499.99,
     'quantity': 1,
     'total': 7499.99,
     'discountPercentage': 11.58,
     'discountedTotal': 6631.49,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp'},
    {'id': 28,
     'title': 'Ice Cream',
     'price': 5.49,
     'quantity': 5,
     'total': 27.450000000000003,
     'discountPercentage': 8.69,
     'discountedTotal': 25.06,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp'},
    {'id': 98,
     'title': 'Rolex Submariner Watch',
     'price': 13999.99,
     'quantity': 2,
     'total': 27999.98,
     'discountPercentage': 5.05,
     'discountedTotal': 26585.98,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'},
    {'id': 8,
     'title': "Dior J'adore",
     'price': 89.99,
     'quantity': 1,
     'total': 89.99,
     'discountPercentage': 14.72,
     'discountedTotal': 76.74,
     'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
    {'id': 162,
     'title': 'Blue Frock',
     'price': 29.99,
     'quantity': 5,
     'total': 149.95,
     'discountPercentage': 12.13,
     'discountedTotal': 131.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
    {'id': 14,
     'title': 'Knoll Saarinen Executive Conference Chair',
     'price': 499.99,
     'quantity': 4,
     'total': 1999.96,
     'discountPercentage': 2.01,
     'discountedTotal': 1959.76,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp'}],
   'total': 37767.32,
   'discountedTotal': 35410.79,
   'userId': 12,
   'totalProducts': 6,
   'totalQuantity': 18},
  {'id': 13,
   'products': [{'id': 35,
     'title': 'Potatoes',
     'price': 2.29,
     'quantity': 2,
     'total': 4.58,
     'discountPercentage': 5.38,
     'discountedTotal': 4.33,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp'},
    {'id': 23,
     'title': 'Eggs',
     'price': 2.99,
     'quantity': 4,
     'total': 11.96,
     'discountPercentage': 11.05,
     'discountedTotal': 10.64,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp'}],
   'total': 16.54,
   'discountedTotal': 14.97,
   'userId': 13,
   'totalProducts': 2,
   'totalQuantity': 6},
  {'id': 14,
   'products': [{'id': 44,
     'title': 'Family Tree Photo Frame',
     'price': 29.99,
     'quantity': 4,
     'total': 119.96,
     'discountPercentage': 14.87,
     'discountedTotal': 102.12,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp'},
    {'id': 68,
     'title': 'Pan',
     'price': 24.99,
     'quantity': 1,
     'total': 24.99,
     'discountPercentage': 3,
     'discountedTotal': 24.24,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp'},
    {'id': 65,
     'title': 'Lunch Box',
     'price': 12.99,
     'quantity': 5,
     'total': 64.95,
     'discountPercentage': 10.34,
     'discountedTotal': 58.23,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/lunch-box/thumbnail.webp'}],
   'total': 209.9,
   'discountedTotal': 184.59,
   'userId': 14,
   'totalProducts': 3,
   'totalQuantity': 10},
  {'id': 15,
   'products': [{'id': 61,
     'title': 'Hand Blender',
     'price': 34.99,
     'quantity': 2,
     'total': 69.98,
     'discountPercentage': 17.02,
     'discountedTotal': 58.07,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp'},
    {'id': 105,
     'title': 'Apple MagSafe Battery Pack',
     'price': 99.99,
     'quantity': 1,
     'total': 99.99,
     'discountPercentage': 17.17,
     'discountedTotal': 82.82,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'},
    {'id': 141,
     'title': 'Basketball Rim',
     'price': 39.99,
     'quantity': 2,
     'total': 79.98,
     'discountPercentage': 7.74,
     'discountedTotal': 73.79,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp'}],
   'total': 249.95,
   'discountedTotal': 214.68,
   'userId': 15,
   'totalProducts': 3,
   'totalQuantity': 5},
  {'id': 16,
   'products': [{'id': 20,
     'title': 'Cooking Oil',
     'price': 4.99,
     'quantity': 5,
     'total': 24.950000000000003,
     'discountPercentage': 9.33,
     'discountedTotal': 22.62,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp'},
    {'id': 91,
     'title': 'Sports Sneakers Off White & Red',
     'price': 119.99,
     'quantity': 3,
     'total': 359.96999999999997,
     'discountPercentage': 4.97,
     'discountedTotal': 342.08,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp'}],
   'total': 384.92,
   'discountedTotal': 364.7,
   'userId': 16,
   'totalProducts': 2,
   'totalQuantity': 8},
  {'id': 17,
   'products': [{'id': 123,
     'title': 'iPhone 13 Pro',
     'price': 1099.99,
     'quantity': 5,
     'total': 5499.95,
     'discountPercentage': 9.37,
     'discountedTotal': 4984.6,
     'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
    {'id': 137,
     'title': 'American Football',
     'price': 19.99,

In [43]:
carts_data.keys()

dict_keys(['carts', 'total', 'skip', 'limit'])

In [44]:
import pandas

In [45]:
carts_df = pandas.DataFrame(carts_data)

In [46]:
carts_df

                                                carts  total  skip  limit
0   {'id': 1, 'products': [{'id': 162, 'title': 'B...    208     0     30
1   {'id': 2, 'products': [{'id': 86, 'title': 'Ma...    208     0     30
2   {'id': 3, 'products': [{'id': 24, 'title': 'Fi...    208     0     30
3   {'id': 4, 'products': [{'id': 92, 'title': 'Sp...    208     0     30
4   {'id': 5, 'products': [{'id': 161, 'title': 'S...    208     0     30
5   {'id': 6, 'products': [{'id': 192, 'title': 'R...    208     0     30
6   {'id': 7, 'products': [{'id': 56, 'title': 'El...    208     0     30
7   {'id': 8, 'products': [{'id': 18, 'title': 'Ca...    208     0     30
8   {'id': 9, 'products': [{'id': 1, 'title': 'Ess...    208     0     30
9   {'id': 10, 'products': [{'id': 41, 'title': 'T...    208     0     30
10  {'id': 11, 'products': [{'id': 115, 'title': '...    208     0     30
11  {'id': 12, 'products': [{'id': 117, 'title': '...    208     0     30
12  {'id': 13, 'products': [{'id': 35, 'title': 'P...    208     0     30
13  {'id': 14, 'products': [{'id': 44, 'title': 'F...    208     0     30
14  {'id': 15, 'products': [{'id': 61, 'title': 'H...    208     0     30
15  {'id': 16, 'products': [{'id': 20, 'title': 'C...    208     0     30
16  {'id': 17, 'products': [{'id': 123, 'title': '...    208     0     30
17  {'id': 18, 'products': [{'id': 169, 'title': '...    208     0     30
18  {'id': 19, 'products': [{'id': 22, 'title': 'D...    208     0     30
19  {'id': 20, 'products': [{'id': 123, 'title': '...    208     0     30
20  {'id': 21, 'products': [{'id': 79, 'title': 'A...    208     0     30
21  {'id': 22, 'products': [{'id': 16, 'title': 'A...    208     0     30
22  {'id': 23, 'products': [{'id': 127, 'title': '...    208     0     30
23  {'id': 24, 'products': [{'id': 117, 'title': '...    208     0     30
24  {'id': 25, 'products': [{'id': 32, 'title': 'M...    208     0     30
25  {'id': 26, 'products': [{'id': 122, 'title': '...    208     0     30
26  {'id': 27, 'products': [{'id': 192, 'title': '...    208     0     30
27  {'id': 28, 'products': [{'id': 182, 'title': '...    208     0     30
28  {'id': 29, 'products': [{'id': 174, 'title': '...    208     0     30
29  {'id': 30, 'products': [{'id': 143, 'title': '...    208     0     30

In [47]:
carts_df.to_csv("dummyjson_carts.csv", index=False)
print("✅ Carts saved to dummyjson_carts.csv")

✅ Carts saved to dummyjson_carts.csv